### ISSUE TITLE
OpenId Auth - BadRequestException: Authentication type not specified

### ISSUE THREAD

**Issue by andymrussell** [serverless-components/graphql#7]
Hi,
When specifying the the auth option for OpenID, I get an error saying:

"BadRequestException: Authentication type not specified"
I believe this is an issue here:
https://github.com/serverless/aws-sdk/blob/b552a3954e6cadb093db4127cb8458192c7bb35b/src/deployAppSyncApi.js

But it could be an issue with how the structure of the yaml in this component.

I don't know if this is something that is not supported yet, a bug, or my bad implementation.

Any help would be appreciated. 

For clarity my serverless.yaml looks like this (with placeholders replaced with real value):

```
component: graphql
name: [my app]-graphql

inputs:
  src: ./build
  auth:
    issuer: https://[domain].auth0.com
    authTTL: 0
    clientId: [my client id]
    iatTTL: 0

**Comment by eahefnawy** [comment]
Fixed. Thanks @andymrussell

**Comment by andymrussell** [comment]
Awesome. What release version would this be going into? 
I just upgraded serverless, but still get the same issue.

Versions:
```
Framework Core: 1.78.1 (standalone)
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.33.4

```


Missing required key 'authenticationType' in params

And when adding the following into serverless.yml

```
inputs:
  src: ./
  region: eu-west-1
  authenticationType: OPENID_CONNECT
```


I then get the previous error again:
Error: Authentication type not specified.


I got the details for the authentication type from here:
https://github.com/serverless/aws-sdk-extra/blob/515802e950e3029872f14b77728c2a2436f93cc3/src/deployAppSyncApi.js

Any help would be much appreciated.
